[package]
name = "rustsign"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
base64 = "0.22"
ed25519-dalek = "2.0.0-pre.1"  # or the version you're using
anyhow = "1.0"